# config/subdomain.yaml
description: "Subdomain enumeration with HTTP probing to identify live subdomains"
name: quick_scan
execution_mode: sequential
tools:
  - name: findomain
    description: Subdomain enumeration
    type: domain_enum
    command: findomain
    flags:
      - flag: "-t"
        option: "Domain"
        required: true
      - flag: "-u"
        option: "Output"
        default: "subdomain_findomain_output.txt"

  - name: httpxbb
    description: httpx for probing discovered subdomains
    command: httpxbb
    type: recon
    flags:
      - flag: "-l"
        option: "Input"
        default: "httpx_input.txt"
      - flag: "-o"
        option: "Output"
        default: "httpx_output.txt"
      - flag: "-silent"
        description: "Run in silent mode"
        is_boolean: true
      - flag: "-t"
        default: "20"
  - name: gowitness
    description: Web screenshot
    command: gowitness
    type: fingerprint
    flags:
      - flag: "scan"
        is_positional: true
      - flag: "file"
        is_positional: true
      - flag: "-f"
        option: "File"
        default: "httpx_output.txt"
        required: true
      - flag: "--screenshot-path"
        option: "ScreenshotPath"
        default: "."
  - name: nmap
    description: Nmap for port scanning live subdomains
    command: nmap
    flags:
      - flag: "-iL"
        option: "Input"
        default: "subdomain_findomain_output.txt"
      - flag: "-oN"
        option: "Output"
        default: "nmap_output.txt"
      - flag: "-sS"
        description: "TCP SYN scan"
        is_flag: true
      - flag: "-Pn"
        description: "Skip host discovery"
        is_flag: true
      - flag: "-p"
        option: "Ports"
        default: "80,443"
      - flag: "-oX"
        option: "Output"
        default: "nmap_output.xml"
      - flag: "-silent"
        description: "Run in silent mode"
        is_flag: true