# config/subdomain.yaml
execution_mode: sequential
tools:
  - name: subfinder
    description: Subdomain discovery
    command: subfinder
    flags:
      - flag: "-d"
        option: "Domain"
        required: true
      - flag: "-o"
        option: "Output"
        default: "subfinder_output.txt"
        
  - name: httpxbb
    description: httpx for probing discovered subdomains
    command: httpxbb
    flags:
      - flag: "-l"  
        option: "Input"
        default: "subfinder_output.txt"
      - flag: "-o"
        option: "Output"
        default: "httpx_output.txt"
      - flag: "-silent"
        description: "Run in silent mode"
        is_flag: true
      - flag: "-t"
        default: "20"
  
  - name: gowitness
    description: Web screenshot
    command: gowitness
    flags:
      - flag: "scan"
        is_positional: true
      - flag: "file"
        is_positional: true
      - flag: "-f"
        option: "File"
        default: "httpx_output.txt"
        required: true
      - flag: "--screenshot-path"
        option: "ScreenshotPath"
        default: "."
      